spring:
  batch:
    job:
      enabled: false
#    names: ioSampleJob
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:hsqldb:mem:testdb
    driverClassName: org.hsqldb.jdbcDriver
    username: sa
    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true    # localhost:8080/h2-console
#      path: /h2-console
#      settings:
#        trace: false
#        web-others: false

logging:
  level:
    root: debug
